export const COLOURS = {
    white: '#fff',
    black:'#000',
    brown:'#795548',
    backgroundLight: '#F0F0F3',
    backgroundMedium: '#B9B9B9',
    backgroundDark: '#777777',
} 

export const Items = [
    {
        id:1,
        category:'shirts',
        productName:'Half slives cotton t-shirt pure cotton ',
        productPrice:1999,
        shipping:60,
        description:'This premium t-shirt is as close to perfect as can be. Its optimized for all types of print and will quickly become your favorite t-shirt The standard, traditional t-shirt for everyday wear Classic, generous, boxy fit Male model shown is 60 / 183 cm tall and wearing size MediumFemale model shown is 58 / 173 cm tall.',
        isOff:true,
        offPercentage:10,
        shippingrate:'60',
        productRating:'5.0',
        productSize:'Large - Medium - Xtralarge',
        productFabric:'97% Cotton',
        productColour:'Black Blue White',
        productImage:require('../images/29.png'),
        isAvailable:true,
        productImageList: [
            require('../images/29.png'),
            require('../images/33.png'),
            require('../images/28.png'),
        ]
    },

    {
        id:2,
        category:'shirts',
        productName:'The Henly -Y neck style',
        productPrice:1299,
        shipping:60,
        description:'The standard, traditional t-shirt for everyday wear Classic, generous, boxy fit Male model shown is 60 / 183 cm tall and wearing size MediumFemale model shown is 58 / 173 cm tall and wearing size SmallHeavyweight 5.3 oz / 180 gsm fabric, solid colors are 100% preshrunk cotton, heather grey is 90% cotton/10% polyester, denim heather is 50% cotton/ 50% polyester Double-needle hems and neck band for durability',
        isOff:false,
        offPercentage:10,
        shippingrate:'60',
        productRating:4.9,
        productSize:'only Large ',
        productFabric:'87% Cotton & 13% Polyster',
        productColour:'Blue Black White',
        productImage:require('../images/32.png'),
        isAvailable:true,
        productImageList: [
            require('../images/32.png'),
            require('../images/33.png'),
            require('../images/28.png'),
        ]
    },

    {
        id:3,
        category:'shirts',
        productName:'Sleeves t-shirt style ',
        productPrice:1099,
        shipping:60,
        description:'This premium t-shirt is as close to perfect as can be 100% cotton (heather gray and heather ice blue are 95%. Its optimized for all types of print and will quickly become your favorite t-shirt. Soft, comfortable and durable, this is a definite must-own',
        isOff:false,
        offPercentage:10,
        shippingrate:'60',
        productRating:4.1,
        productSize:'only Medium - Large  ',
        productFabric:'100% Cotton',
        productColour:'Black Blue White',
        productImage:require('../images/33.png'),
        isAvailable:false,
        productImageList: [
            require('../images/33.png'),
            require('../images/33.png'),
            require('../images/28.png'),
        ]
    },

    {
        id:4,
        category:'shirts',
        productName:'Polo t-shirt collar style',
        productPrice:1499,
        shipping:60,
        description:'This premium t-shirt is as close to perfect as can be. Its optimized for all types of print and will quickly become your favorite t-shirt. Soft, comfortable and durable, this is a definite must-own  Heather blue & charcoal gray are 80% cotton/20% polyester.',
        isOff:true,
        offPercentage:15,
        shippingrate:'60',
        productRating:3.2,
        productSize:'only Small - Large',
        productFabric:'70% Cotton',
        productColour:'White Black Blue',
        productImage:require('../images/28.png'),
        isAvailable:true,
        productImageList: [
            require('../images/28.png'),
            require('../images/33.png'),
            require('../images/28.png'),
        ]
    },

    {
        id:5,
        category:'shirts',
        productName:'Raglan sleeves types',
        productPrice:1199,
        shipping:60,
        description:'The standard, traditional t-shirt for everyday wear Classic, generous, boxy fit Male model shown is 60 / 183 cm tall and wearing size MediumFemale model shown is 58 / 173 cm tall and wearing size SmallHeavyweight 5.3 oz / 180 gsm fabric, solid colors are 100% preshrunk cotton, heather grey is 90% cotton/10% polyester, denim heather is 50% cotton/ 50% polyester Double-needle hems and neck band for durability',
        isOff:true,
        offPercentage:10,
        shippingrate:'60',
        productRating:'3.0',
        productSize:'only Small - Large',
        productFabric:'70% Cotton',
        productColour:'White Black Blue',
        productImage:require('../images/40.png'),
        isAvailable:true,
        productImageList: [
            require('../images/40.png'),
            require('../images/37.png'),
            require('../images/28.png'),
        ]
    },

    {
        id:6,
        category:'shirts',
        productName:'Polo Half length sleeves types',
        productPrice:1250,
        shipping:60,
        description:'This premium t-shirt is as close to perfect as can be. Its optimized for all types of print and will quickly become your favorite t-shirt The standard, traditional t-shirt for everyday wear Classic, generous, boxy fit Male model shown is 60 / 183 cm tall and wearing size MediumFemale model shown is 58 / 173 cm tall.',
        isOff:false,
        offPercentage:10,
        shippingrate:'60',
        productRating:'4.0',
        productSize:'only Small - Large',
        productFabric:'70% Cotton',
        productColour:'White Black Blue',
        productImage:require('../images/39.png'),
        isAvailable:true,
        productImageList: [
            require('../images/39.png'),
            require('../images/33.png'),
            require('../images/28.png'),
        ]
    },


    {
        id:7,
        category:'shirts',
        productName:'Baggy style t-shirt',
        productPrice:1599,
        shipping:60,
        description:'The standard, traditional t-shirt for everyday wear Classic, generous, boxy fit Male model shown is 60 / 183 cm tall and wearing size MediumFemale model shown is 58 / 173 cm tall and wearing size SmallHeavyweight 5.3 oz / 180 gsm fabric, solid colors are 100% preshrunk cotton, heather grey is 90% cotton/10% polyester, denim heather is 50% cotton/ 50% polyester Double-needle hems and neck band for durability',
        isOff:false,
        offPercentage:10,
        shippingrate:'60',
        productRating:'3.9',
        productSize:'only Small - Large',
        productFabric:'70% Cotton',
        productColour:'White Black Blue',
        productImage:require('../images/38.png'),
        isAvailable:true,
        productImageList: [
            require('../images/38.png'),
            require('../images/33.png'),
            require('../images/28.png'),
        ]
    },


    {
        id:8,
        category:'shirts',
        productName:'Muscle fit style t-shirt',
        productPrice:1999,
        shipping:60,
        description:'This premium t-shirt is as close to perfect as can be. Its optimized for all types of print and will quickly become your favorite t-shirt The standard, traditional t-shirt for everyday wear Classic, generous, boxy fit Male model shown is 60 / 183 cm tall and wearing size MediumFemale model shown is 58 / 173 cm tall.',
        isOff:true,
        offPercentage:20,
        shippingrate:'60',
        productRating:3.8,
        productSize:'only Small - Large',
        productFabric:'70% Cotton',
        productColour:'White Black Blue',
        productImage:require('../images/37.png'),
        isAvailable:true,
        productImageList: [
            require('../images/37.png'),
            require('../images/40.png'),
            require('../images/28.png'),
        ]
    },

    // jeans start

    {
        id:9,
        category:'jeans',
        productName:'Loose Fit Jeans style',
        productPrice:1200,
        shipping:60,
        description:'Loose Fit Jeans style or randomly Feel free is a durable cotton or cotton-blend twill (twill is a type of weave) textile, typically used to make jeans, overalls and other types of clothing. It is a strong fabric made using the warp and weft weaving method which results in a diagonal denim ribbing. In the US, denim has been used old and Mature peoples .',
        isOff:false,
        offPercentage:15,
        shippingrate:'60',
        productRating:'3.0',
        productSize:'36 west ',
        productFabric:'Cotton jeans ',
        productColour:'0riginal Jeans colour ',
        productImage:require('../images/30.png'),
        isAvailable:false,
        productImageList: [
            require('../images/30.png'),
            require('../images/34.png'),
            require('../images/35.png'),
        ]
    },
    {
        id:10,
        category:'jeans',
        productName:'Regular style Jeans',
        productPrice:1350,
        shipping:60,
        description:'Regular style Jeans or casualjeans is a durable cotton or cotton-blend twill (twill is a type of weave) textile, typically used to make jeans, overalls and other types of clothing. It is a strong fabric made using the warp and weft weaving method which results in a diagonal denim ribbing. In the US, denim has been used since the mid-19th century.',
        isOff:true,
        offPercentage:17,
        shippingrate:'60',
        productRating:'4.0',
        productSize:'28 west ',
        productFabric:'100% Cotton jeans',
        productColour:'0riginal Jeans colour ',
        productImage:require('../images/jeans.png'),
        isAvailable:true,
        productImageList: [
            require('../images/jeans.png'),
            require('../images/30.png'),
            require('../images/34.png'),
        ]
    },

    {
        id:11,
        category:'jeans',
        productName:'tapered Damage Jeans',
        productPrice:1500,
        shipping:60,
        description:'Tepered Damge Jeans is a durable cotton or cotton-blend twill (twill is a type of weave) textile, typically used to make jeans, overalls and other types of clothing. It is a strong fabric made using the warp and weft weaving method which results in a diagonal denim ribbing. In the US, denim has remove from other sites .',
        isOff:true,
        offPercentage:10,
        shippingrate:'60',
        productRating:'4.3',
        productSize:'34 west',
        productFabric:'Adidas Jeans',
        productColour:'0riginal Jeans colour ',
        productImage:require('../images/36.png'),
        isAvailable:true,
        productImageList: [
            require('../images/36.png'),
            require('../images/jeans.png'),
            require('../images/34.png'),
        ]
    },

    {
        id:12,
        category:'jeans',
        productName:'Slim Fit style Jeans',
        productPrice:1050,
        shipping:60,
        description:'Denim is a durable cotton or cotton-blend twill (twill is a type of weave) textile, typically used to make jeans, overalls and other types of clothing. It is a strong fabric made using the warp and weft weaving method which results in a diagonal denim ribbing. In the US, denim has been used old and Strong People.',
        isOff:false,
        offPercentage:10,
        shippingrate:'60',
        productRating:'3.9',
        productSize:'30 west ',
        productFabric:'Denim Jeans',
        productColour:'0riginal Jeans colour ',
        productImage:require('../images/34.png'),
        isAvailable:true,
        productImageList: [
            require('../images/34.png'),
            require('../images/30.png'),
            require('../images/jeans.png'),
        ]
    },

    {
        id:13,
        category:'jeans',
        productName:'Narrow style Fit Jeans',
        productPrice:1099,
        shipping:60,
        description:'Narrow style Fit Jeans or cotton-blend twill (twill is a type of weave) textile, typically used to make jeans, overalls and other types of clothing. It is a strong fabric made using the warp and weft weaving method which results in a diagonal denim ribbing. In the US, denim has been used since the Made this.',
        isOff:false,
        offPercentage:10,
        shippingrate:'60',
        productRating:'4.7',
        productSize:'30 west ',
        productFabric:'Denim Jeans',
        productColour:'0riginal Jeans colour ',
        productImage:require('../images/42.png'),
        isAvailable:true,
        productImageList: [
            require('../images/42.png'),
            require('../images/30.png'),
            require('../images/jeans.png'),
        ]
    },

    {
        id:14,
        category:'jeans',
        productName:'Relaxed style Fit Jeans',
        productPrice:1799,
        shipping:60,
        description:'Relaxed Fit Jeans style of fabric shirt named after the T shape of its body and sleeves. Traditionally, it has short sleeves and a round neckline, known as a crew neck, which lacks a collar. t-shirts are generally made of a stretchy, light, and inexpensive fabric and are easy to clean. The t-shirt evolved from undergarments used in the 19th century and, in the mid-20th century, transitioned from undergarment to general-use casual clothing.',
        isOff:true,
        offPercentage:13,
        shippingrate:'60',
        productRating:'4.2',
        productSize:'30 west ',
        productFabric:'Denim Jeans',
        productColour:'0riginal Jeans colour ',
        productImage:require('../images/43.png'),
        isAvailable:true,
        productImageList: [
            require('../images/43.png'),
            require('../images/30.png'),
            require('../images/jeans.png'),
        ]
    },

]